### ISSUE TITLE
Visible release updates info

### ISSUE THREAD

**Issue by hp115** [MDAnalysis/UserGuide#338]
It would be nice to have a short and easy-to-find section with a summary of new release updates and features.

**Comment by RMeli** [comment]
Interesting suggestion. Maybe one possibility is to parse automatically the release notes on GitHub?

**Comment by IAlibay** [comment]
I've opened #339 to fix this. Unfortunately this would have to be (for now) a semi-automatic process because:

1. We can't easily access GH_TOKEN on places like RTD (or even using subprocess in our own actions)
2. Checking that the notes render well is going to need some kind of human intervention

I'm hoping we can stick the file generation into the release action eventually though, that would save time / thinking.
