### ISSUE TITLE
Add an author list

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/UserGuide#60]
The authors of the user guide are hardcoded as `Lily Wang, Richard J Gowers, Oliver Beckstein` somewhere but @RMeli has now contributed and hopefully others will. I think the MDAnalysis docs sort contributors in alphabetical order but stick @nmichaud first and @orbeckst last -- should there be a similar scheme for the user guide?

**Comment by richardjgowers** [comment]
Yeah good idea. I’d follow the same model, put you/Lily first, Oliver last,
me penultimate then alphabetical.

**Comment by RMeli** [comment]
I can speak only for myself, but I don't think fixing a few typos and formatting while I read along (great work btw!) really counts as contribution in the grand scheme of the User Guide; such "contributions" are tracked by `git` anyway. 

But I agree something similar to MDAnalysis can be done for more substantial contributions.

**Comment by orbeckst** [comment]
In MDAnalysis we decided to include every contribution as an author; partly to encourage contributions through visible credit, partly because often people contribute more and then when do you decide to tell them that “this is now enough for an entry in AUTHORS”, and partly because it makes us look good because it demonstrates that this is a true community effort.
