### ISSUE TITLE
More dependencies

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/UserGuide#66]
Add:
* tqdm
* tidynamics (pending https://github.com/MDAnalysis/mdanalysis/pull/2619)
* sphinx==1.8.5 (and other doc dependencies, as an additional section)

to the dependencies for installation the development environment.

**Comment by orbeckst** [comment]
I added `tqdm` to https://github.com/MDAnalysis/mdanalysis/wiki/Style-Guide#list-of-core-module-dependencies

**Comment by lilyminium** [comment]
Thanks. Should we continue keeping two copies of the same info?

**Comment by orbeckst** [comment]
> Thanks. Should we continue keeping two copies of the same info?
Not if I can help it ;-). We just have to agree where the ultimate source is located. 

I am happy to make the User Guide's dev section authoritative. Then link everything to the UG + add a note that in order to update the lists, one has to submit a PR to the UG; basically, tell devs to edit the corresponding page on GitHub and submit it as a PR. We then also have to make sure that at least all core-devs are able to merge PRs in the UG. Can we raise a UG issue to hash this out where we can also properly ping the core-devs?

**Comment by orbeckst** [comment]
Oops, I overlooked that this _is_ already an issue in the UG... and this is as good as any to discuss.

@MDAnalysis/coredevs are we happy to transition information from the wiki (especially enaything related to Style Guide, core modules, and other "musts" in development) to the dev section of the User Guide?

**Comment by lilyminium** [comment]
Sounds good to me! Another issue (maybe meriting its own actual issue) -- should there be distinct develop/master guide docs paralleling the API docs? (i.e. mdanalysis.org/docs vs mdanalysis.org/mdanalysis)

Simply because a fair number of people download the dev version for features that haven't been released yet and it would be handy to point them towards a guide that matches. It also makes it easier to update the develop version alongside new features instead of doing a big update for every release.

**Comment by orbeckst** [comment]
Good idea, especially as you already have a version that's for "1.0".  What's a good name? UserGuideDev, DevUserGuide, LatestUserGuide ... – which reminds me, mdtraj's docs  managed to implement the versioning of RTD into their own docs.  IIRC the conversation that wasn't entirely trivial but doable. That might be the neatest solution in the long run. In the short run, two versions would be just fine.
