### ISSUE TITLE
Publish 1.0 version

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/UserGuide#70]
With 1.0 released https://github.com/MDAnalysis/mdanalysis/issues/2443 there should also be the 1.0 version of the user guide online.  At the moment it is 0.20.1.

**Comment by lilyminium** [comment]
ANALYSIS: REVIEW
- [ ] aligning structures -- mention `match_atoms` etc
- [ ] rms -- added `weights_groupselections`
- [ ] contacts.Contacts -- added radius_cut_q
- [ ] encore -- dres returns dimensionality reduction details instead of reference to self. hes does not accept details keyword anymore.
- [ ] polymer.PersistenceLength
- [ ] PCA (now correctly aligns; also some other fun new methods)
- [ ] GNM -- removed `MassWeight` option

ANALYSIS: ADD
- [ ] align.AverageStructure
- [ ] HydrogenBondAnalysis
- [ ] hole2
- [ ] DensityAnalysis

OTHER: ADD
- [ ] ParmEd
- [ ] Notebook execution scripts
- [ ] other scripts; add to conf.py

**Comment by orbeckst** [comment]
I think you can close it... I see https://userguide.mdanalysis.org/

**Comment by lilyminium** [comment]
Yeah, I was going to make my way down the https://github.com/MDAnalysis/UserGuide/issues/70#issuecomment-643726274 checklist and close some other issues but it has been quite slow going...

**Comment by orbeckst** [comment]
I would open a new issue for the checklist – that will allow you to get the warm, fuzzy feeling from closing this issue!

(Never mind that you will have opened another one...)

**Comment by orbeckst** [comment]
I moved the laundry lists to #98 and #99 so that I can close this issue.

```
closed issues    -1
opened issues    +2
--------------------
net issues       +1
```

☹️
